version: "3.7"
services:
  application:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - database
  database:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      - "MYSQL_ROOT_PASSWORD=password"
      - "MYSQL_DATABASE=gruppen"

    # volumes:
    #   - "./mysql/db/storage:/var/lib/mysql"
