[header]#Projekt der Gruppe "Gruppen1"#

== [big underline]#Softwareentwicklung im Team: Vorbereitung auf das Projekt#

== Management Summary zum Gruppenbildungs - Projekt

=== Problemstatement

Das primäre Ziel des Projektes ist, eine Self-Contained-System bereitzustellen, welches die
Funktion der

* Gruppenbildung
** Gruppensuche nach bestehenden Gruppen

bereitstellt. Dies soll das Organisieren von eigenen Lerngruppen/Abgabengruppen und das gemeinsame Arbeiten an
Vorlesungsinhalten und/oder Übungsblättern erleichtern.

Bisher war es umständlich und zeitaufwendig eine Gruppe zum Lernen und/oder für Abgaben zu finden. +
Insbesondere für Studierende, die noch nicht viele Kommilitonen kennengelernt haben, ist dies aktuell problematisch.

== Wesentliche Features und Ziele des Projekts

Das Gruppenbildungsprojekt ist ein Self-Contained-System, welches Schnittstellen zu:

* Materialsammlung
* Terminfindung
* Foren
* Abgabensystem

bietet.

Wesentliche Features sind:

* Einfache Erstellung von Gruppen
* Suche nach bestehenden Gruppen
* Schutz der Privatsphäre durch restringierte Gruppen
* Zuordnung einer Veranstaltung zu einer Gruppe
* Festlegung der Gruppengröße für eine potentielle Gruppenabgabe

== Hinweise zu Dokumentationen

* Als *primäre* Referenz für die Funktionalität der Anwendung dient die
https://github.com/hhu-propra2/abschlussprojekt-die-senioren/blob/master/Dokumentation/dokumentation.adoc[Dokumentation].
* Als *sekundäre* Referenz kann das
https://github.com/hhu-propra2/abschlussprojekt-die-senioren/wiki/[Wiki] herangezogen werden.
Im Wiki befinden sich verschiedenste Dokumentationen zu einzelnen Aspekten des Projekts.

== Starten der Anwendung

*Linux und MacOS*

Um die Anwendung zu starten, muss der Befehl `docker-compose up` aus dem Root - Verzeichnis
des Projektes heraus ausgeführt werden. +
Danach läuft die Anwendung auf Port 8080. (localhost:8080/gruppen1/)

*Windows*

Um die Anwendung zu starten, muss *vor* dem clonen des Projektes lokal der
Befehl `git config --global core.autocrlf false` ausgeführt werden.

Ist das Projekt anschließend gecloned, kann die Anwendung mit dem Befehl `docker-compose up --build`
aus dem Root - Verzeichnis des Projektes gestartet werden.