== Dokumentation der Software - Architektur des Gruppenbildungsprojekt

Dieses Dokument dient sowohl der Dokumentation, als auch der Kommunikation der
Software - Archtitektur des Gruppenbildungs - Projekts. +
Die vorliegende Dokumentation orientiert sich dabei am https://www.arc42.de[arc42 - Template] für Software -
Architektur Dokumentationen.

== Einführung und Ziele

Dieser Abschnitt führt in die Aufgabenstellung des
Gruppenbildungsprojekts ein und soll die Ziele, sowohl
die geschäftlichen als auch Qualitätsziele, darlegen.

=== Aufgabenstellung

Das primäre Ziel des Projektes ist, eine Self-Contained-System bereitzustellen, welches die
Funktionen der

* Gruppenbildung
** Gruppensuche nach bestehenden Gruppen
* Gruppenarbeit
* Gruppenabgaben
** Zuordnung einer Veranstaltung zu einer Gruppe

vereint, sodass diese Funktionalitäten in der Zukunft nicht mehr verstreut sind über mehrere
Systeme. Dies soll das Organisieren von eigenen Lerngruppen und das gemeinsame Arbeiten an
Vorlesungsinhalten und/oder Übungsblättern erleichtern.

Ein weiteres Ziel ist, dass dieses System Schnittstellen zu weiteren Systemen
bieten soll, in denen die studentischen Gruppen relevant sind. +
Diese Systeme sind:

* Materialsammlung
* Terminfindung
* Foren
* Abgabesystem

=== Qualitätsziele

Die folgende Tabelle beschreibt die Qualitätsziele des
Gruppenbildungssystems. +
Dabei spielt die Reihenfolge *keine Rolle* bezüglich der
Wichtigkeit der Ziele.

|===
|*Qualitätsziel*|*Motivation & Erläuterung*
|Leicht zugänglich & übersichtlich| User des Gruppenbildungssystems sollen
sich schnell zurecht finden. Dabei soll die UI nur notwendigste
Elemente besitzen.
|Autarkes SCS, Modularität|Die verwendete Onion - Architektur sorgt dafür,
dass externe Komponenten wie Datenbanken leicht ausgetauscht werden können,
da Abhängigkeiten zu externen Services vermieden werden.
|Gute Performance|Durch eine eventbasierte Datenbank, sowie schnellen
In - Memory Datenstrukturen wird eine gute Performance des Systems gewährleistet.
|===