name: CITesting

on:
    push:
        branches:
            - '**'
    pull_request:
        branches:
            - master
            - CITesting

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 12
      - name: Run Check
        run:  gradle check
